version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /c/Users/Aromanen/Desktop/praca magisterska/practical-part/praca-magisterska/nexus-data:/nexus-data