version: '3.8'

services:
  rest-apps:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8081"
      - "8092:8082"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    networks:
      - rest-network

networks:
  rest-network:
    driver: bridge 